version: 2.1
orbs:
  win: circleci/windows@5.0
  matlab: mathworks/matlab@0
  
executors:
  linux: # a Linux VM running Ubuntu 20.04 
    machine:
      image: ubuntu-2204:2024.01.1
  macos: # macos executor running Xcode
    macos:
      xcode: 15.1.0
    resource_class: macos.x86.medium.gen2
  windows:
    win/default
  
jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >> 
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: ver
          
workflows:
  tests-on-all-platforms:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux, macos, windows]
