version: 2.1
orbs:
  matlab: mathworks/matlab@0

jobs:
  build:
    environment:
      MATHWORKS_RMC_BASE_URL: https://mw-ci-static-dev.s3.amazonaws.com/run-matlab-command/v1
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: ver
      - matlab/run-tests:
          source-folder: code
