version: 2.1
orbs:
  win: circleci/windows@4.1.1 # The Windows orb give you everything you need to start using the Windows executor.
jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run:
          name: check env
          command: |
            curl https://mw-ci-static-dev.s3.amazonaws.com/matlab-deps/v0/versions.json | jq .semantic.r2021a
          shell: bash
# Test
