version: 2.1
orbs:
  win: circleci/windows@5.0
  matlab: mathworks/matlab@1

executors:
  linux: # a Linux VM running Ubuntu 20.04 
    machine:
      image: ubuntu-2404:current
  
jobs:
  build:
    environment:
      MATHWORKS_LICENSING_ENDPOINT: dev
    parameters:
      os:
        type: executor
    executor: << parameters.os >> 
    steps:
      - checkout
      - run: env
      - matlab/install
      - matlab/run-command:
          command: ver
      - matlab/run-tests:
          source-folder: code
          use-parallel: true
          
workflows:
  tests-on-all-platforms:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux]
