version: 2.1
orbs:
  matlab: mathworks/matlab@dev:v1-beta
  codecov: codecov/codecov@1
env:
  MATHWORKS_LICENSING_ENDPOINT: stage
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run: echo $MATHWORKS_LICENSING_ENDPOINT
      - matlab/install:
      - matlab/run-tests:
          source-folder: code
          code-coverage-html: test-results
      - store_artifacts:
          path: test-results
      # As an alternative to run-tests, you can use run-command to execute a MATLAB script, function, or statement.
      # - matlab/run-command:
