version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:edge
    steps:
      - checkout
      - run:
          name: check env
          command: |
            curl https://mw-ci-static-dev.s3.amazonaws.com/matlab-deps/v0/versions.json | jq .semantic.r2021a
          shell: bash
# Test
