version: 2.1
orbs:
  matlab: mathworks/matlab@0
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests:
          source-folder: code
          test-results-html: test-results
      - store_artifacts:
          path: test-results
