version: 2.1
orbs:
  matlab: mathworks/matlab@dev:v1-rc
jobs:
  build:
    environment:
      MATHWORKS_LICENSING_ENDPOINT: stage
      # MATHWORKS_RMC_BASE_URL: https://ssd.mathworks.com/supportfiles/ci/run-matlab-command/v2
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: ver
      - matlab/run-tests:
          source-folder: code
