version: 2.1
orbs:
  matlab: mathworks/matlab@dev:eff1a24864b611b9f5ed2bf894b1a9704c053d7b
jobs:
  build:
    environment:
      MATHWORKS_RMC_BASE_URL: https://mw-ci-static-dev.s3.amazonaws.com/run-matlab-command/v2
      MATHWORKS_LICENSING_ENDPOINT: stage
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      - checkout
      - matlab/install:
          release: r2023a
      - matlab/run-command:
          command: ver
