version: 2.1
orbs:
  matlab: mathworks/matlab@0
jobs:
  build:
    machine:
      image: ubuntu-2204
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: ver
