version: 2.1
orbs:
  matlab: mathworks/matlab@dev:v1-beta
jobs:
  build:
    machine:
      image: ubuntu-latest
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: ver
