version: 2.1
orbs:
  matlab: mathworks/matlab@0
  codecov: codecov/codecov@1
jobs:
  build:
    machine:
      image: ubuntu-2204:edge
    steps:
      - checkout
      - run:
          name: check env
          command: |
            echo $CIRCLECI
            echo $CIRCLE_REPOSITORY_URL
            echo $CIRCLE_PROJECT_USERNAME
            echo $CIRCLE_PROJECT_REPONAME
            echo $CIRCLE_BUILD_NUM
          shell: bash
      - matlab/install
      - matlab/run-command:
          command: "license inuse"
# Test
