on: [push]

env:
  MATHWORKS_LICENSING_ENDPOINT: stage

jobs: 
  my-job-v2-rc:
    name: Test Workflow
    strategy:
      matrix:
        os: [ubuntu-latest] # [windows-2022, ubuntu-22.04, macos-12]
        release: [r2023a]
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-rc0
        with:
          release: ${{ matrix.release }}
          products: Simulink_Test

      - name: Run command
        uses: matlab-actions/run-command@v2-rc0
        with:
          command: disp(string(matlabpath).split(":")
          
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-rc0
        with:
          release: ${{ matrix.release }}
          products: CI/CD_Automation_for_Simulink_Check

      - name: Run command
        uses: matlab-actions/run-command@v2-rc0
        with:
          command: disp(string(matlabpath).split(":")

      - name: Run command
        uses: matlab-actions/run-command@v2-rc0
        with:
          command: processAdvisorExampleStart
