name: MATLAB matrix build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: "Parallel_Computing_Toolbox && ls"
      - name: Run MATLAB Command
        uses: matlab-actions/run-command@v2
        with:
          command: ver
