on: [push]
jobs: 
  my-job:
    name: Run Build
    runs-on: ubuntu-24.04
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@bash
        with:
          release: latest-including-prerelease
      - run: matlab-batch -v
