on: [push]
jobs: 
  my-job:
    name: Run Build
    runs-on: windows-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4
      - run: grep --help
        shell: bash
