on: [push]
jobs: 
  my-job-v2:
    name: Run Tests V2
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]
        release: [r2023b]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4

      # Sets up MATLAB on the GitHub Actions runner  
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.release }}

      - name: Run command
        uses: matlab-actions/run-command@v2
        with:
          command: ver
          startup-options: -nodisplay
          
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v2
        with:
          source-folder: code
          startup-options: -nodisplay 
