name: Run MATLAB Build on GitHub-Hosted Runner
on: [push]
jobs:
  my-job:
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
      - name: Run Tests
        uses: matlab-actions/run-tests@v1
        with:
          test-results-junit: test-results/results.xml
          source-folder: code
