name: Run MATLAB Build on GitHub-Hosted Runner
on: [push]

jobs: 
  my-job:
    name: Run Command
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Run Comamand
        uses: matlab-actions/run-command@v1
        with:
          command: disp(pwd);
