on: [push]
jobs: 
  my-job:
    name: Run Build
    runs-on: macos-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: r2021a
      - name: Run function using parfor
        uses: matlab-actions/run-command@v2
        with:
          command: parfor i = 1:10; i; end
