name: Run MATLAB Build on GitHub-Hosted Runner
on: [push]
jobs: 
  my-job:
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run MATLAB Build
        uses: matlab-actions/run-build@v1
