name: Run MATLAB Build on GitHub-Hosted Runner
on: [push]
jobs: 
  my-job:
    name: Run Command
    runs-on: windows-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: r2020b

      - name: Run Comamand
        uses: matlab-actions/run-command@v1
        with:
          command: pwd
          startup-options: -log
