name: Run MATLAB Build on GitHub-Hosted Runner
on: [push]
jobs: 
  my-job:
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2019b
      - run: matlab -batch "license inuse"
      - name: Run MATLAB Command
        uses: matlab-actions/run-command@v1
        with:
          command: license inuse
      - name: Test eMATLAB
        run: matlab -batch "c = mex.getCompilerConfigurations; arrayfun(@(config)disp(config), c)"
          
