on: [push]
jobs: 
  my-job:
    name: Run Build
    runs-on: ubuntu-24.04
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: latest-including-prerelease
      - name: Run command
        uses: matlab-actions/run-command@v1
        with:
          command: ver
