on: [push] # Run workflow on every push

jobs:
  matlab-build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]
        release: [r2023b]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-prerelease
        with:
          release: latest-including-prerelease
          cache: true
      - name: Run tests
        uses: matlab-actions/run-tests@v2
