on: [push]
env:
  MATHWORKS_INSTALLER_BASE_URL: "https://mpmtest.s3.amazonaws.com"
jobs: 
  my-job:
    name: Run Tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        release: [r2023b]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4

      # Sets up MATLAB on the GitHub Actions runner  
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.release }}

      - name: Run command
        run: matlab -batch "magic(10)"
