on: [push] # Run workflow on every push
env:
  MW_MATLAB_BATCH_URL_OVERRIDE: https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v0/
  MATHWORKS_ACCOUNT: ${{ secrets.MATHWORKS_ACCOUNT }}
  MATHWORKS_TOKEN: ${{ secrets.MATHWORKS_TOKEN }}

jobs:
  matlab-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-prerelease
        with:
          release: latest-including-prerelease
          products: Parallel_Computing_Toolbox
          
      - name: Patch for v0 matlab-batch
        run: wget -qO- --retry-connrefused https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v0/install.sh | bash -s

      - name: Run tests
        uses: matlab-actions/run-build@v1
