on: [push] 

env:
  MATHWORKS_LICENSING_ENDPOINT: stage

jobs:
  my-job-v2-rc:
    name: Test Workflow
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]
        release: [r2023b]
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-rc
        with:
          release: ${{ matrix.release }}

      - name: Check path
        uses: matlab-actions/run-command@v2-rc0
        with:
          command: ver

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-rc
        with:
          release: ${{ matrix.release }}
