name: Run MATLAB Build on GitHub-Hosted Runner
on: [push]
jobs: 
  my-job:
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: R2022bU3
      - name: Run MATLAB Command
        uses: matlab-actions/run-command@v1
        with:
          command: license inuse
          
