name: MATLAB build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install MATLAB dependencies
      run: >
        export DEBIAN_FRONTEND=noninteractive &&
        sudo apt-get update &&
        sudo apt-get install -y $(wget -qO- https://raw.githubusercontent.com/mathworks-ref-arch/container-images/refs/heads/main/matlab-deps/r2024b/ubuntu24.04/base-dependencies.txt)
    - name: Setup MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: r2024b
    - name: Run command
      uses: matlab-actions/run-command@v2
      with:
        command: ver
