name: Run MATLAB Tests
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matlab-actions/setup-matlab@v2
        with:
          products: |
            Simulink
            Simulink_Test
            Parallel_Computing_Toolbox
      - uses: matlab-actions/run-tests@v2
        with:
          use-parallel: true
