# This workflow runs a matrix build with both versions of setup MATLAB action

name: MATLAB matrix build

# Controls when the action will run.
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  nogpu:
    strategy:
      matrix:
        # Run this workflow on different os
        os: [ubuntu-24.04]
      fail-fast: false
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v6
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          products: MATLAB_Test
      - name: Run Tests
        uses: matlab-actions/run-tests@v3
        with:
          source-folder: code
          code-coverage-cobertura: results/cobertera.xml
