name: Run MATLAB Build on GitHub-Hosted Runner
on: [push]
env:
  MATHWORKS_LICENSING_ENDPOINT: stage
jobs:
  my-job:
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
      - run: matlab -batch "license inuse"
      - name: Run MATLAB Command
        uses: matlab-actions/run-command@v1
        with:
          command: license inuse
      - name: Test eMATLAB
        run: matlab -batch "disp('yo world')"
          
