on: [push] # Run workflow on every push
env:
  MW_MATLAB_BATCH_URL_OVERRIDE: https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v0/
  MATHWORKS_ACCOUNT: ${{ secrets.MATHWORKS_ACCOUNT }}
  MATHWORKS_TOKEN: ${{ secrets.MATHWORKS_TOKEN }}

jobs:
  matlab-build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]
        release: [r2023b]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-prerelease
        with:
          release: latest-including-prerelease
          products: Parallel_Computing_Toolbox
          
      - name: Patch for v0 matlab-batch
        run: curl -s https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v0/install.sh | bash -s
        shell: bash

      - name: Run tests
        uses: matlab-actions/run-build@v1
