on: [push]
jobs: 
  my-job:
    name: Run Tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        release: [r2023b]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4

      # Sets up MATLAB on the GitHub Actions runner  
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2

      - run: matlab-batch version
      
      - name: Run command
        uses: matlab-actions/run-command@v2
        with:
          command: magic(10)
