name: MATLAB build
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  MATHWORKS_LICENSING_ENDPOINT: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup MATLAB
      uses: matlab-actions/setup-matlab@v2
    - name: Run command
      uses: matlab-actions/run-command@v2
      with:
        command: ver
