on: [push]
env:
  MATHWORKS_LICENSING_ENDPOINT: stage
jobs: 
  my-job-v2-rc:
    name: Run Tests V2
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v3

      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-rc0
        with:
          release: r2023a
          products: Simulink Simulink_Test
          cache: true

      - name: Run command
        uses: matlab-actions/run-command@v2-rc0
        with:
          command: disp("hello world!")
          
      # Runs a set of commands using the runners shell
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v2-rc0
        with:
          source-folder: code
