on: [push] # Run workflow on every push
env:
  MW_MATLAB_BATCH_URL_OVERRIDE: https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v0/

jobs:
  matlab-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-prerelease
        with:
          release: latest-including-prerelease
        
      - name: Run tests
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: src
