# This workflow runs a matrix build with both versions of setup MATLAB action

name: MATLAB matrix build

# Controls when the action will run.
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        # Run this workflow on different os
        command: ["ver;", "ver;", "ver;", "ver;", "ver;", "ver;", "ver;"]
      fail-fast: false
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: latest-including-prerelease
          products: Symbolic_Math_Toolbox
      - name: Run MATLAB Command
        uses: matlab-actions/run-command@v2
        with:
          command: ${{ matrix.command }}
